name:                symchar
version:             0.1.0.0
github:              "mlyean/symchar"
license:             BSD-3-Clause
author:              "Ming Yean Lim"
maintainer:          "example@example.com"
copyright:           "2024 Ming Yean Lim"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mlyean/symchar#readme>

dependencies:
- base >= 4.7 && < 5
- data-memocombinators >= 0.5.1 && < 0.6
- bytestring >= 0.12 && < 0.13

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  symchar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - symchar

tests:
  symchar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - symchar
